version: '3.6'
services:  
  
  generate:
    build:
      context: "./.."
      dockerfile: docker/generate.Dockerfile
    command: |
      /scripts/wait-for-it.sh db:5432 -- bash -c '
      sql-migrate up
      echo migrations DONE
      rm -f /usr/local/codegen/generated-models/*
      sqlboiler psql --add-global-variants -o ./generated-models
      echo ORM code generation DONE'
    links:
      - db
    ports:
      - 36480:8080
    environment:
      DB_NAME: "dbname"
      DB_HOST: "db"
      DB_USER: "dbuser"
      DB_PASS: "dbpass"
      DB_PORT: "5432"
    volumes:
      - "../generated-models:/usr/local/codegen/generated-models"
  
  db:
    image: postgres:10.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpass"